In [1]:
import cv2
import numpy as np

# Load the predefined dictionary
dictionary = cv2.aruco.Dictionary_get(cv2.aruco.DICT_6X6_250)

# Initialize the detector parameters using default values
parameters = cv2.aruco.DetectorParameters_create()

# Load the image
image = cv2.imread('./images/main.jpg')

# Convert the image to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Detect the markers in the image
corners, ids, rejectedImgPoints = cv2.aruco.detectMarkers(gray, dictionary, parameters=parameters)

# If any markers are detected, draw them on the image
if len(corners) > 0:
    cv2.aruco.drawDetectedMarkers(image, corners, ids)

# Display the result
# cv2.imshow('Image with detected ArUco markers', image)
# cv2.waitKey(0)
# cv2.destroyAllWindows()


In [2]:
print(corners)

(array([[[883., 771.],
        [958., 772.],
        [957., 847.],
        [882., 845.]]], dtype=float32), array([[[1358.,  456.],
        [1282.,  455.],
        [1282.,  381.],
        [1358.,  382.]]], dtype=float32))


In [6]:
for corner in corners:
    for i in corner:
        print(i)

[[883. 771.]
 [958. 772.]
 [957. 847.]
 [882. 845.]]
[[1358.  456.]
 [1282.  455.]
 [1282.  381.]
 [1358.  382.]]


In [7]:
x = [(948, 804), (1348, 418)]

In [9]:
x[0][0]

948